version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-task_manager_db}
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ["/app/docker-entrypoint.sh"]

  postgres:
    image: postgres:14-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-task_manager_db}
    # Removed persistent volume to ensure fresh database on each run
